[WIP] Add paper_finder
jsk-ros-pkg/jsk_recognition pull request #2542
Opened 2020-11-11 07:33 UTC by iory

# What is this?

Detect papers (rectangle) and publish posearray.

@Kanazawanaoaki 

![RViz-_001](https://user-images.githubusercontent.com/4690682/98782562-88b27800-243b-11eb-9fd1-41cc138f45f5.png)

2021-07-07 02:24 UTC, k-okada requested changes
@iory @Kanazawanaoaki could you creaet documentation for this node?

2021-07-13 03:45 UTC, iory commented
@Kanazawanaoaki
Have you tried this program?
Can you create a document for your skill up?

2021-12-01 13:11 UTC, k-okada commented
@s-yuzaki 外部のpipなしで動くようにしました．先程入れた一式は，一旦pip uninstall / pip2 uninstall しても大丈夫です．．．．．が，今の状態で動いているので，まずはbagファイルとつなげるところを先にやって，それが動いたら，こちらを試してみるのがよいとおもいます．

@Kanazawanaoaki ドキュメント書いてみましょう．

2021-12-05 03:25 UTC, s-yuzaki commented
連絡遅れてすみません、先週取ったbagファイルから紙を認識できました。ありがとうございます。

2021-12-06 01:54 UTC, merged

2021-12-06 01:54 UTC, k-okada commented
@Kanazawanaoaki @s-yuzaki 確認ありがとうございます．