Add hand keypoints tracking node_script
jsk-ros-pkg/jsk_recognition pull request #2597
Opened 2021-05-16 07:48 UTC by W567

Add hand_pose_estimation_2d.py to [jsk_perception].
Add hand_pose msgs to [jsk_recognition_msgs].

2021-05-19 15:41 UTC, knorth55 commented
I can download the model from google drive!

2021-05-19 15:46 UTC, knorth55 commented
@W567 can you add sample launch for this node as `human_mesh_recovery` node?
you can refer to this sample launch.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/sample/sample_human_mesh_recovery.launch

I also want you to add documentation as this one.
https://jsk-docs.readthedocs.io/projects/jsk_recognition/en/latest/jsk_perception/nodes/people_pose_estimation_2d.html
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/doc/jsk_perception/nodes/people_pose_estimation_2d.rst

2021-05-19 15:49 UTC, knorth55 requested changes

2021-05-19 15:49 UTC, knorth55 commented on jsk_recognition_msgs/msg/HandPose.msg
> +geometry_msgs/Pose[] poses
how about using adding score field as `PeoplePose` msg?
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_recognition_msgs/msg/PeoplePose.msg

2021-05-20 01:41 UTC, W567 commented
@knorth55 Thank you for your information and advice, I will deal with those parts.

2021-05-24 15:31 UTC, closed without merging

2021-05-24 15:33 UTC, knorth55 commented
@W567 please do not use `master` branch for PR. please use another branch to make a PR.