[WIP] add GPU/CUDA information on 18.04 / PyTorch
jsk-ros-pkg/jsk_recognition pull request #2612
Opened 2021-07-09 08:14 UTC by k-okada

add 'How to install CUDA` information, based on discussion at https://github.com/jsk-ros-pkg/jsk_recognition/pull/2601#issuecomment-876405219

2021-07-09 08:52 UTC, 708yamaguchi commented on doc/install_chainer_gpu.rst
>      pip install -vvv cupy --no-cache-dir
`cupy==6.7.0`??

2021-07-09 08:55 UTC, knorth55 commented
in my understanding, the easiest way for melodic 18.04 is as follow:

apt:
  nvidia-driver-390
  nvidia-cuda-toolkit: 9.1
pip:
  chainer==6.7.0
  cupy-cuda91==6.7.0
  torch==1.1.0
  torchvision==0.3.0

or we can use rocker with CUDA_VISIBLE_DEVICES

2021-07-11 14:35 UTC, knorth55 requested changes

2021-07-11 14:35 UTC, knorth55 commented on doc/install_chainer_gpu.rst
> +  ```
```suggestion
- Ubuntu 18.04 : You can use CUDA 9.1 by deafult

  ```bash
  sudo apt install nvidia-cuda-toolkit
  sudo apt install nvidia-cuda-dev
  ```
```

2021-07-12 02:16 UTC, knorth55 approved these changes

2021-09-09 09:43 UTC, merged