Enable 3d hand pose detection
jsk-ros-pkg/jsk_recognition pull request #2672
Opened 2022-04-07 11:22 UTC by nakane11

Updated hand pose estimation to get hand pose in 3d．
Since the previous rosbag data doesn't include depth image, I replaced it with new one compatible．

`roslaunch jsk_perception sample_hand_pose_estimation_2d_for_pr2.launch GPU:=-1 with_depth:=true`

Cc: @iory

2022-04-07 14:16 UTC, tkmtnt7000 commented
Nice PR!
I think it is very good feature. 

Maybe I am overthinking this, but I'm a little concerned about the potential for confusion with file names.
The node file name is `hand_pose_estimation_"2d".py`, but this node gives us "3d" hand pose in addition to 2d hand pose.

2022-04-07 14:40 UTC, Affonso-Gui commented
(was thinking the same thing, but am not sure which would be the right way to proceed. Maybe keeping the `hand_pose_estimation_2d.py` and adding a new `hand_pose_estimation_3d.launch` and `sample_hand_pose_estimation_3d.launch`? Or just removing the "2d" part from the file name altogether if it doesn't cause any compatibility issues..)

2022-04-07 15:12 UTC, iory commented
This node originally estimates the pixel position of hands. 
In my opinion, estimating the 3d position is an optional feature of this node.

> Maybe keeping the hand_pose_estimation_2d.py and adding a new hand_pose_estimation_3d.launch and sample_hand_pose_estimation_3d.launch?

So we don't have to erase `2d` and I agree with this idea.

2022-04-08 00:24 UTC, knorth55 commented
Good PR!
IMO, there is another solution for further development.
I think it might be useful to separate this feature to one node like `HandPose2Dto3D`,
which subscribe 2D `HandPoseArray`, `DepthImage`, `CameraInfo` and publish 3d `HandPoseArray`.
But, this PR looks good to me.

FYI:
I made `PeoplePose2Dto3D` to separate the simliar feature.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2641

2022-04-08 10:36 UTC, Affonso-Gui commented
@knorth55 Also seems nice, specially considering we have the `PeoplePose2Dto3D` precedent

2022-04-08 13:20 UTC, iory requested changes

2022-04-08 13:20 UTC, iory commented on doc/jsk_perception/nodes/hand_pose_estimation_2d.rst
> +* ``~output/pose2d`` (``jsk_recognition_msgs/HandPoseArray``)
``~output/pose_2d``  is correct.

2022-04-08 14:31 UTC, nakane11 commented on doc/jsk_perception/nodes/hand_pose_estimation_2d.rst
> +* ``~output/pose2d`` (``jsk_recognition_msgs/HandPoseArray``)
I revised it.

2022-04-08 14:56 UTC, iory approved these changes

2022-04-08 14:57 UTC, iory commented on doc/jsk_perception/nodes/hand_pose_estimation_2d.rst
> +* ``~output/pose2d`` (``jsk_recognition_msgs/HandPoseArray``)
Nice!

2022-04-10 10:41 UTC, merged