[jsk_perception] Use logdebug when height for label is not specified
jsk-ros-pkg/jsk_recognition pull request #2709
Opened 2022-07-01 12:24 UTC by 708yamaguchi

`rect_array_in_panorama_to_bounding_box_array.py` works fine even if label height is not specified.
However, even in that case, warning continue to be outputted to terminal.

Based on the issue https://github.com/jsk-ros-pkg/jsk_robot/issues/1518, I use `rospy.logdebug` when height for label is not specified.

2022-07-03 02:09 UTC, k-okada requested changes
I would suggest to add
```
rospy.logwarn_once('height for label "{}" (id:{}) is not specified'.format(label_name,label_id))
rospy.logdebug('height for label "{}" (id:{}) is not specified'.format(label_name,label_id))
```
or `throttle` or `throttle_identical`, because if someone start using they node in different environment,  thye wan to to check if they have configured correctly, as you originally put this line.
http://wiki.ros.org/rospy/Overview/Logging#Logging_Once

2022-07-04 14:42 UTC, 708yamaguchi commented
@k-okada 
Thank you very much for your review.

I use throttle_identical logging for label height check.
[`7e06436` (#2709)](https://github.com/jsk-ros-pkg/jsk_recognition/pull/2709/commits/7e064361fc790ed2ae094c0d7b78b7ae44bbddd2)

2022-07-04 14:43 UTC, 708yamaguchi commented
In addition, I found that input warning keeps to be published in fetch robot case.
This is because panorama object detection is not selected when fetch robot is started.
To throttle this warning, I use throttle_identical logging for input check, too.
```
[WARN] [1656706605.613080] [/edgetpu_panorama_object_detection_rect_array_in_panorama_to_bounding_box_array:rosout]: subscribing topic seems not to be pulished. waiting... Error: timeout exceeded while waiting for message on topic ~input_class
[WARN] [1656706608.619924] [/edgetpu_panorama_object_detection_rect_array_in_panorama_to_bounding_box_array:rosout]: subscribing topic seems not to be pulished. waiting... Error: timeout exceeded while waiting for message on topic ~input_class
[WARN] [1656706611.628611] [/edgetpu_panorama_object_detection_rect_array_in_panorama_to_bounding_box_array:rosout]: subscribing topic seems not to be pulished. waiting... Error: timeout exceeded while waiting for message on topic ~input_class
[WARN] [1656706614.635127] [/edgetpu_panorama_object_detection_rect_array_in_panorama_to_bounding_box_array:rosout]: subscribing topic seems not to be pulished. waiting... Error: timeout exceeded while waiting for message on topic ~input_class
[WARN] [1656706617.645581] [/edgetpu_panorama_object_detection_rect_array_in_panorama_to_bounding_box_array:rosout]: subscribing topic seems not to be pulished. waiting... Error: timeout exceeded while waiting for message on topic ~input_class
```

[`9bb3f2d` (#2709)](https://github.com/jsk-ros-pkg/jsk_recognition/pull/2709/commits/9bb3f2d4991c14acc580ce33d68c4c186372c588)

2022-07-15 08:46 UTC, iory approved these changes

2022-07-16 06:08 UTC, merged