[jsk_pcl/OrganizedStatisticalOutlierRemoval] support several pointcloud type
jsk-ros-pkg/jsk_recognition pull request #2846
Opened 2024-09-25 01:24 UTC by knorth55

this PR supports several point cloud type as `xyzirt`.
now this nodes only support `xyzrgb`.

2024-09-27 09:18 UTC, mqcmd196 commented
? What happened to CI?

```
Post job cleanup.
/usr/bin/docker exec  3bc6fc00c[2](https://github.com/jsk-ros-pkg/jsk_recognition/actions/runs/11024597303/job/30618033143?pr=2846#step:11:2)a0cb532a512f8729db5968edbb17067e62fe9ffca5b3e5eb87e008 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

2024-10-29 11:29 UTC, k-okada commented
```
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/organized_statistical_outlier_removal_nodelet.cpp: In member function ?virtual void jsk_pcl_ros::OrganizedStatisticalOutlierRemoval::filterCloud(pcl::PCLPointCloud2::Ptr, pcl::PointIndices::Ptr, bool)?:
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/organized_statistical_outlier_removal_nodelet.cpp:170:47: error: no matching function for call to ?pcl::StatisticalOutlierRemoval<pcl::PCLPointCloud2>::filter(std::vector<int>&)?
       sor.filter(pcl_indices_filtered->indices);
                                               ^
In file included from /usr/include/pcl-1.8/pcl/filters/filter_indices.h:43:0,
                 from /usr/include/pcl-1.8/pcl/filters/statistical_outlier_removal.h:43,
                 from /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/organized_statistical_outlier_removal_nodelet.cpp:39:
/usr/include/pcl-1.8/pcl/filters/filter.h:238:7: note: candidate: void pcl::Filter<pcl::PCLPointCloud2>::filter(pcl::Filter<pcl::PCLPointCloud2>::PCLPointCloud2&)
       filter (PCLPointCloud2 &output);
       ^~~~~~
/usr/include/pcl-1.8/pcl/filters/filter.h:238:7: note:   no known conversion for argument 1 from ?std::vector<int>? to ?pcl::Filter<pcl::PCLPointCloud2>::PCLPointCloud2& {aka pcl::PCLPointCloud2&}?
make[2]: *** [CMakeFiles/jsk_pcl_ros.dir/src/organized_statistical_outlier_removal_nodelet.cpp.o] Error 1
make[1]: *** [CMakeFiles/jsk_pcl_ros.dir/all] Error 2
make: *** [all] Error 2
cd /workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros; catkin build --get-env jsk_pcl_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```
https://github.com/jsk-ros-pkg/jsk_recognition/actions/runs/11564823139/job/32190755001?pr=2846

2024-12-03 01:36 UTC, knorth55 commented
😢 `pcl-1.9`
https://github.com/PointCloudLibrary/pcl/pull/1663

2024-12-04 01:02 UTC, knorth55 commented
```
Run actions/checkout@v2
/usr/bin/docker exec  c3c01c40fd0b135ec9f5458b2a24ada205a0270039fa36574e29b9c29012b6a9 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

`GLIBC_2.28` error again :(

2024-12-05 02:12 UTC, mqcmd196 commented
> GLIBC_2.28 error again :(

Some people point out the same issue. I also can't find the official announcement... https://github.com/orgs/community/discussions/145711

2024-12-05 02:16 UTC, mqcmd196 commented
https://github.blog/changelog/2024-09-25-end-of-life-for-actions-node16/

I think we cannot use `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true` any more...

2024-12-05 02:24 UTC, knorth55 commented
:sob

2024-12-29 00:40 UTC, k-okada requested changes
@knorth55 
could you resolve conflicts?

2024-12-29 02:44 UTC, knorth55 commented
@k-okada Hi, I resolved the conflict by rebasing this PR.

2025-04-29 05:23 UTC, merged